### PR TITLE
Remove stray </li> tag and use <iref> again

### PR DESCRIPTION
**Pull request by timsong-cpp**
Basically the same thing as #72. One day this will be automated...one day.

### CODE REVIEW

**Comment by timsong-cpp** [comment]
Updated to current master.

Perhaps we should teach the program to recognize `<a href="lwg-(closed|active|defects).html#NNNN">NNNN</a>` as internal links and treat them like `<iref>`?

**Comment by mclow** [comment]
Maybe I should teach the program that generates those summaries to use `iref`.

**Comment by timsong-cpp** [comment]
My understanding last time I looked into this is that the summaries are copied from the HTML lists? In those lists, `<a>` is the right thing to generate. You'd need to teach them to generate a separate summary with `<iref>`.

**Comment by mclow** [comment]
Ok, I've added an instruction to do so into `how-to-docs.html`  Thanks for the reminder.

**Pull request merged**
