### PR TITLE
Remove unused .travis.yml file

### PR DESCRIPTION
**Pull request by jwakely**
GitHub Actions replaced the Travis CI two years ago. Add the checks for carriage returns and valid XML to the new CI config.

### CODE REVIEW

**Comment by jwakely** [comment]
Do we want to restore these CI checks which stopped running when Travis CI was decommissioned?

**Comment by Dani-Hub** [comment]
> Do we want to restore these CI checks which stopped running when Travis CI was decommissioned?

I have no strong opinion. What is your preference?

**Comment by jwakely** [comment]
There were quite a lot of XML validation errors that I fixed in 97cae0d651206ee0892998c0ee02e4ce68147441. If we re-enabled validation in the CI that would be avoided.

**Comment by Dani-Hub** [comment]
> There were quite a lot of XML validation errors that I fixed in [97cae0d](https://github.com/cplusplus/LWG/commit/97cae0d651206ee0892998c0ee02e4ce68147441). If we re-enabled validation in the CI that would be avoided.

Great, so lets do it!

**Pull request merged**
