### PR TITLE
Allow generating and updating the HTML files incrementally

### PR DESCRIPTION
**Pull request by timsong-cpp**
The first few commits are mostly cleanup. 

- For instance, several `report_generator` member functions each make three `multiset<issue, order_by_{first_tag|status}>`, copying _all the issues_ twice (and active issues thrice) in the process. The only use for these multisets is to determine how many issues share the same tag/status with a certain issue. That's now represented as three `unordered_map<std::string, int>`s and built once in `report_generator`'s constructor.

- To generate the diff, we run a comparison on old and new metadata. But instead of just using the `vector<issue>` we already have, `lists.cpp` builds a brand-new `vector<tuple<int, string>>`  just for the diffing. It no longer does that.

On to the main feature, the basic idea is:
- The build script is responsible for maintaining
   - `mailing/commit`: the hash of the current commit
   - `mailing/commit.prev`: the hash of the commit last time the build script is run
   - `mailing/changed_files.txt`: this is the list of files that changed between the two commits identified above.
- `bin/lists` uses `mailing/changed_files.txt` together with `mailing/lwg-toc.html` to determine which files require regeneration and how. It writes to `mailing/updated_files.txt` a list of files it regenerated.
- The update script checks that `mailing/commit.prev` matches `gh-pages/commit`. If so, then it performs an incremental update by just copying those files in `mailing/updated_files.txt` and updates `gh-pages/commit` to `mailing/commit`. Otherwise, it falls back to performing a full copy. It should be possible to make this more clever (it should be safe to do an incremental update if `mailing/commit.prev` is an ancestor of `gh-pages/commit` - provided that the latter is an ancestor if `mailing/commit`), but it's not clear to me if that's really a problem.

This has been lightly tested. Up to bdc040a, the generated output matches the current software modulo the changes intentionally introduced by be51fad and 1cceea4 and timestamp differences. On a quick test (Ubuntu running in Windows Subsystem for Linux, with all relevant files on a SSD), I see a 2x overall speedup when changing the content of a single issue file (i.e., not affecting other issues at all).

Also, no batch files yet. They make my head explode.

### CODE REVIEW

**Comment by timsong-cpp** [comment]
Batch files are now up. No promises that they are great batch files - if such a thing even exists - but they seem to work OK in my tests.

I can't find a batch equivalent to `xargs`, so the batch file will only do an incremental update if the number of files is less than 300 (an arbitrarily chosen number). The problem is that when the number is too large (e.g., a full rebuild), copying and adding one file at a time will decimate performance.

**Comment by timsong-cpp** [comment]
Based on Daniel's description of his workflow, this shifts management of the baseline for incremental generation to `update_lists_incremental`. This means that `build_lists_only_incremental` doesn't need to error out on dirty working directories, because it no longer affects the baseline. However, `update_lists_incremental` will refuse to update when the list is built from a dirty working directory, because there's no way to identify the baseline content in that case. Since in this setup the metadata should not change with every build, we now keep `mailing/lwg-toc.prev.html` as the previous metadata, updated together with `mailing/commit.prev` by `update_lists_incremental`.

The workflow should remain identical modulo appending `_incremental`s at the end of the script call and ensuring that the WD is clean before calling the final `build_lists_only_incremental` followed by `update_lists_incremental`.

**Comment by CaseyCarter** [comment]
FYI, I stomped on your `.gitignore` change.

**Comment by timsong-cpp** [comment]
Rebased.

**Comment by timsong-cpp** [comment]
I also have [an additional patch](https://github.com/timsong-cpp/LWG/commit/9ebde240f4abaa550d8e1e610f0ead92f0593f8f) sitting in a separate branch that further generates per-project (i.e., `IS`, `fund.ts.v2`, `networking.ts`, etc.) ready/immediate/editor lists, as Marshall alluded to a while ago. I'll make a PR after this one is disposed of.

**Pull request closed without merging**
