### PR TITLE
Fix MSVC STL typo

### PR DESCRIPTION
**Pull request by hewillk**

### CODE REVIEW

**Comment by hewillk** [comment]
Hum, maybe I don’t have permission to submit a pull request here, but thank you for merging it.

**Comment by Dani-Hub** [comment]
Are you wondering why you don't see an immediate change in the active issue list? This will become visible, once we rebuild the list again (We don't do that automatically for each accepted PULL request)

**Comment by hewillk** [comment]
I mean, I just found out that most of the people who submitted the pull request are committee members, so I just wondered whether or not a normal user can submit a pull request if it's just a typo.

**Comment by Dani-Hub** [comment]
Everyone can, there is no need to be a member of some club ;-)

**Comment by timsong-cpp** [comment]
I'm not so sure this is a typo - MSFT is a common abbreviation of "Microsoft", and "MSFTSTL" is certainly a plausible way to refer to that implementation (which doesn't seem to have a widely used shorthand name). @CaseyCarter?

**Comment by jwakely** [comment]
> so I just wondered whether or not a normal user can submit a pull request if it's just a typo.

Definitely!

But as Tim said, this one wasn't a typo. MSFT is the ticket symbol for Microsoft on NASDAQ. The change seems fine anyway though. In the context of C++, "MSVC" is probably more easily identified.

**Pull request merged**
