### PR TITLE
3150: Rebase wording onto the post-San Diego working draft

### PR DESCRIPTION
**Pull request by CaseyCarter**

### CODE REVIEW

**Comment by mclow** [comment]
This is a result of the conversation that you are having with Richard, right?

**Comment by CaseyCarter** [comment]
P1084 changed the meaning of deduction constraints (`{ E } -> Concept<Args...>;`) and directed the editors to replace occurrences of `E; requires Concept<decltype((E)), Args...>;` with the former pattern in [concepts].  Richard decided to editorially make the same change everywhere else in cplusplus/draft@b7d7dde75d39a3790c49c765adc5b590a0634376 saving me the trouble of submitting a followup paper to clean up the other occurrences.

This PR updates the context wording around the proposed change to agree with what will be in the post-SD working draft.

**Comment by CaseyCarter** [comment]
Force-pushed a new commit with the actual N number for the post-San Diego working draft.

**Comment by CaseyCarter** [comment]
> Force-pushed a new commit with the actual N number for the post-San Diego working draft.

And again, since the post-San Diego working draft changed numbers from n4788 to n4791.

**Pull request merged**
