### PR TITLE
Update wording for LWG 3622 and 3833

### PR DESCRIPTION
**Pull request by timsong-cpp**

### CODE REVIEW

**Comment by Dani-Hub** [comment]
@timsong-cpp Can you rebase the wording to N4928?

**Comment by timsong-cpp** [comment]
Done (trivially - I don't think there are relevant changes for these two)

**Comment by Dani-Hub** [comment]
Thanks! @jwakely : I'm merging now, but I cannot rebuild the issue list from the place I'm sitting at. Can you do that? If no hurry is needed, I will do that this evening Germany time.

**Comment by jwakely** [comment]
I've rebuilt the lists - thank you both.

**Pull request merged**
