### PR TITLE
Add PR for 3525

### PR DESCRIPTION
**Pull request by timsong-cpp**

### CODE REVIEW

**Comment by Dani-Hub** [comment]
Maybe the trailing-return-type should be omitted as currently suggested for LWG 3526?

**Comment by timsong-cpp** [comment]
I didn't add new ones, but left the existing ones intact.

I'm no longer sure this PR is correct, though... closing this for now, will reopen when I'm sure.

**Comment by Dani-Hub** [comment]
I understand that these are new ones. I was just suggesting whether new ones should follow LWG 3526's approach (unless you object to that approach, of-course).

**Comment by timsong-cpp** [comment]
The new ones being added don't have trailing-return-types, only the existing ones.

**Comment by Dani-Hub** [comment]
Ah, yes, I see now - I misread your pull request!

**Comment by timsong-cpp** [comment]
@Dani-Hub OK, I added a new PR, but kept my first attempt as a superseded PR with an explanation on why that one doesn't work.

I also split out the drive-by fix into a new issue

**Pull request merged**
