### PR TITLE
Apply LEWG prioritization and SG assignment from Kona meeting.

### PR DESCRIPTION
**Pull request by jyasskin**
This is ~half of the issues in LEWG status. I made up SG6 status and picked "Dup" to mark that we have an issues.isocpp.org bug to replace the LWG issue.

### CODE REVIEW

**Comment by jyasskin** [comment]
Ping

**Comment by mclow** [comment]
I haven't forgotten; just was in San Jose for LLVM devcon this Wed/Thu/Fri.

**Comment by mclow** [comment]
Jeffrey - Are we working from the same list of priorities?

Here's what we use:
Priority 1 - Fundamentally broken; DO NOT ship a standard w/o resolving this.
Priority 2 - serious bug.
Priority 3 - default priority.
Priority 4 - minor bug.

I bring this up because you've marked 0255 as P1, and the bug is 15 years old. We've shipped the standards (03/11/14) with this problem.

**Comment by jyasskin** [comment]
I think we took P1 as "we should really fix this for the next feasible standard", rather than for things that could actually delay a standard. Clearly nothing in the LEWG list actually delays standards.

I can revise the patch to cap priorities at P2.

**Comment by jyasskin** [comment]
Btw, are your priorities written down anywhere? We couldn't find them in our Kona session.

**Comment by mclow** [comment]
Writing them down? There's an idea :-) I'll work on that.
I would appreciate you updating the patch to not have any P1s

**Comment by mclow** [comment]
I believe that this has all been applied.

**Pull request closed without merging**
